[package]
name = "sqlparser_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "sqlparser_ffi"
path = "src/lib.rs"
crate_type = ["cdylib"]

[dependencies]
serde_json = "1.0"
libc = "0.2.85"

[dependencies.sqlparser]
version = "0.11.0"
features = ["serde"]