name: mysqldb
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  path: ^1.8.0
  protobuf:
  fixnum:
  args:
  async: ^2.5.0
  collection: ^1.15.0
  convert: any
  crypto: ^3.0.1
  sqlparser_ffi:
    path: ../sqlparser_ffi

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
