name: dorm
description: Dart ORM, Inspire by SQLAlchemy.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path:
  galileo_sqljocky5:
  # sqflite_common:
  sqlite3:
  sqlparser:
  # postgrest:



dev_dependencies:
  lints:
  test:
