name: dorm
description: Dart ORM, Inspire by SQLAlchemy.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path:
  sqlite3:
  # postgrest:
  reflection_factory:
  mysqldb:
    path: ../mysqldb

dev_dependencies:
  lints:
  test:
  build_runner: ^2.1.1
